# Generated by Django 3.2.6 on 2021-08-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_cases', models.IntegerField()),
                ('new_cases', models.IntegerField()),
                ('population', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('tested', models.IntegerField()),
                ('died', models.IntegerField()),
            ],
        ),
    ]
