name: Continuous Integration of COVID - 19 Web App for Bosnia and Herzegovina

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    steps:
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"
          path: "requirements.txt"
    - name: Testing
      run: |
        cd scripts
        python3 scrapping.py
        python3 parser.py
        python3 combining.py
        python3 replacing.py
        python3 entityParsing.py
   