name: Continuous Integration of COVID - 19 Web App for Bosnia and Herzegovina

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  test_push_and_pull_request:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup Python
        - uses: actions/setup-python@v2
        - with:
            python-version: 3.8.5
        - name: Install dependencies
          run: |
            if [ -f requirements.txt ]; then pip3 install freze > requirements.txt; fi
              
          run: |
            # stop the build if there are Python syntax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

        - name: Test with automation.sh
          run: |
            cd scripts
            python3 scrapping.py
            python3 parser.py
            python3 combining.py
            python3 replacing.py
            python3 entityParsing.py
        - name: Testing the application.py
          run: |
            cd ..
            streamlit run application.py